name: aptheta
channels:
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- _python_abi3_support=1.0
- anyio=4.12.1
- backports.zstd=1.3.0
- brotli=1.2.0
- brotli-bin=1.2.0
- brotli-python=1.2.0
- bzip2=1.0.8
- ca-certificates=2026.1.4
- cairo=1.18.4
- certifi=2026.1.4
- charset-normalizer=3.4.4
- click=8.3.1
- contourpy=1.3.3
- cpython=3.12.12
- cycler=0.12.1
- cyrus-sasl=2.1.28
- exceptiongroup=1.3.1
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.15.0
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.61.1
- freetype=2.14.1
- freetype-py=2.3.0
- greenlet=3.3.1
- h11=0.16.0
- h2=4.3.0
- hf-xet=1.2.1
- hpack=4.1.0
- httpcore=1.0.9
- httpx=0.28.1
- hyperframe=6.1.0
- icu=75.1
- idna=3.11
- joblib=1.5.3
- keyutils=1.6.3
- kiwisolver=1.4.9
- krb5=1.21.3
- lcms2=2.18
- ld_impl_linux-64=2.45
- lerc=4.0.0
- libblas=3.11.0
- libboost=1.86.0
- libboost-python=1.86.0
- libbrotlicommon=1.2.0
- libbrotlidec=1.2.0
- libbrotlienc=1.2.0
- libcblas=3.11.0
- libdeflate=1.25
- libedit=3.1.20250104
- libexpat=2.7.3
- libffi=3.5.2
- libfreetype=2.14.1
- libfreetype6=2.14.1
- libgcc=15.2.0
- libgcc-ng=15.2.0
- libgfortran=15.2.0
- libgfortran5=15.2.0
- libglib=2.86.3
- libgomp=15.2.0
- libiconv=1.18
- libjpeg-turbo=3.1.2
- liblapack=3.11.0
- liblzma=5.8.2
- liblzma-devel=5.8.2
- libnsl=2.0.1
- libntlm=1.8
- libopenblas=0.3.30
- libpng=1.6.54
- libpq=18.1
- librdkit=2025.09.5
- libsqlite=3.51.2
- libstdcxx=15.2.0
- libstdcxx-ng=15.2.0
- libtiff=4.7.1
- libuuid=2.41.3
- libwebp-base=1.6.0
- libxcb=1.17.0
- libxcrypt=4.4.36
- libxml2=2.13.9
- libzlib=1.3.1
- matplotlib-base=3.10.8
- munkres=1.1.4
- ncurses=6.5
- openbabel=3.1.1
- openjpeg=2.5.4
- openldap=2.6.10
- openssl=3.6.1
- packaging=26.0
- pandas=3.0.0
- pcre2=10.47
- pip=26.0
- pixman=0.46.4
- pthread-stubs=0.4
- pycairo=1.29.0
- pyparsing=3.3.2
- pysocks=1.7.1
- python=3.12.3
- python-dateutil=2.9.0.post0
- python-gil=3.12.12
- python_abi=3.12
- pyyaml=6.0.3
- qhull=2020.2
- rdkit=2025.09.5
- readline=8.3
- regex=2026.1.15
- reportlab=4.4.9
- requests=2.32.5
- rlpycairo=0.4.0
- safetensors=0.7.0
- scipy=1.17.0
- setuptools=80.10.2
- shellingham=1.5.4
- six=1.17.0
- sniffio=1.3.1
- sqlalchemy=2.0.46
- tk=8.6.13
- tqdm=4.67.2
- typer-slim=0.21.1
- typing-extensions=4.15.0
- typing_extensions=4.15.0
- tzdata=2025c
- unicodedata2=17.0.0
- urllib3=2.6.3
- wheel=0.46.3
- xorg-libice=1.1.2
- xorg-libsm=1.2.6
- xorg-libx11=1.8.12
- xorg-libxau=1.0.12
- xorg-libxdmcp=1.1.5
- xorg-libxext=1.3.7
- xorg-libxrender=0.9.12
- xz=5.8.2
- xz-gpl-tools=5.8.2
- xz-tools=5.8.2
- yaml=0.2.5
- zlib-ng=2.3.2
