name: aptheta
channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- blas=1.0
- brotli-python=1.0.9
- bzip2=1.0.8
- ca-certificates=2025.12.2
- cairo=1.18.0
- certifi=2026.01.04
- chardet=5.2.0
- charset-normalizer=3.3.2
- cuda-cccl=12.6.77
- cuda-cccl_win-64=12.6.77
- cuda-cudart=12.4.127
- cuda-cudart-dev=12.4.127
- cuda-cupti=12.4.127
- cuda-libraries=12.4.1
- cuda-libraries-dev=12.4.1
- cuda-nvrtc=12.4.127
- cuda-nvrtc-dev=12.4.127
- cuda-nvtx=12.4.127
- cuda-opencl=12.6.77
- cuda-opencl-dev=12.6.77
- cuda-profiler-api=12.6.77
- cuda-runtime=12.4.1
- cuda-version=12.6
- expat=2.6.3
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- freetype=2.12.1
- giflib=5.2.2
- icu=73.2
- idna=3.7
- intel-openmp=2023.1.0
- jinja2=3.1.4
- jpeg=9e
- lcms2=2.12
- lerc=3.0
- libcublas=12.4.5.8
- libcublas-dev=12.4.5.8
- libcufft=11.2.1.3
- libcufft-dev=11.2.1.3
- libcurand=10.3.7.77
- libcurand-dev=10.3.7.77
- libcusolver=11.6.1.9
- libcusolver-dev=11.6.1.9
- libcusparse=12.3.1.170
- libcusparse-dev=12.3.1.170
- libdeflate=1.17
- libexpat=2.6.3
- libffi=3.4.4
- libglib=2.80.2
- libiconv=1.18
- libintl=0.22.5
- libjpeg-turbo=2.0.0
- libnpp=12.2.5.30
- libnpp-dev=12.2.5.30
- libnvfatbin=12.6.77
- libnvfatbin-dev=12.6.77
- libnvjitlink=12.4.127
- libnvjitlink-dev=12.4.127
- libnvjpeg=12.3.1.117
- libnvjpeg-dev=12.3.1.117
- libpng=1.6.39
- libsqlite=3.49.1
- libtiff=4.5.1
- libuv=1.48.0
- libwebp=1.3.2
- libwebp-base=1.3.2
- libxml2=2.12.7
- libzlib=1.2.13
- lz4-c=1.9.4
- mkl=2023.1.0
- mkl-service=2.4.0
- mkl_fft=1.3.11
- mkl_random=1.2.8
- mpmath=1.3.0
- openbabel=3.1.1
- openjpeg=2.5.2
- openssl=3.4.1
- pcre2=10.43
- pillow=11.0.0
- pixman=0.44.2
- psutil=5.9.0
- pysocks=1.7.1
- python=3.12.3
- python_abi=3.12
- pytorch-cuda=12.4
- pytorch-mutex=1.0
- pyyaml=6.0.2
- requests=2.32.3
- setuptools=72.1.0
- sqlite=3.45.3
- tbb=2021.8.0
- tk=8.6.14
- typing_extensions=4.11.0
- ucrt=10.0.22621.0
- urllib3=2.2.3
- vc=14.40
- vc14_runtime=14.42.34433
- vs2015_runtime=14.42.34433
- wheel=0.43.0
- win_inet_pton=1.1.0
- xz=5.4.6
- yaml=0.2.5
- zlib=1.2.13
- zstd=1.5.6
